---
namespace: fmjstudios
name: monitoring
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: Ansible Collection for monitoring tools setup and configuration
license_file: "LICENSE"
tags:
  - grafana
  - prometheus
  - promtail
  - loki
  - logrotate
dependencies:
  prometheus.prometheus: ">=0.5.1"
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: https://fmj.dev
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github